[package]
name = "jarvis-update"
version.workspace = true
edition.workspace = true

[dependencies]
jarvis-protocol.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
reqwest.workspace = true
tracing.workspace = true
tokio.workspace = true
